/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessRouteImport } from './routes/access'
import { Route as ActivateRouteImport } from './routes/activate'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as GateRouteImport } from './routes/gate'
import { Route as LoginRouteImport } from './routes/login'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ModerationRouteImport } from './routes/moderation'
import { Route as NotEligibleRouteImport } from './routes/not-eligible'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StandardsRouteImport } from './routes/standards'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as BlogTelegramRoleManagementGuideRouteImport } from './routes/blog.telegram-role-management-guide'
import { Route as BrandAssetSplatRouteImport } from './routes/brand-asset.$'
import { Route as DiscordInteractionsRouteImport } from './routes/discord.interactions'
import { Route as DiscordLinkedRoleRouteImport } from './routes/discord.linked-role'
import { Route as GSlugRouteImport } from './routes/g.$slug'
import { Route as GateMediaSplatRouteImport } from './routes/gate-media.$'
import { Route as GatesIndexRouteImport } from './routes/gates.index'
import { Route as GatesIdRouteImport } from './routes/gates.$id'
import { Route as PreviewRotatingCtaRouteImport } from './routes/preview.rotating-cta'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiInternalTelegramDestinationRouteImport } from './routes/api.internal.telegram-destination'
import { Route as DiscordLinkedRoleCallbackRouteImport } from './routes/discord.linked-role.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateRoute = ActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const GateRoute = GateRouteImport.update({
  id: '/gate',
  path: '/gate',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ModerationRoute = ModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const NotEligibleRoute = NotEligibleRouteImport.update({
  id: '/not-eligible',
  path: '/not-eligible',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StandardsRoute = StandardsRouteImport.update({
  id: '/standards',
  path: '/standards',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogTelegramRoleManagementGuideRoute =
  BlogTelegramRoleManagementGuideRouteImport.update({
    id: '/blog/telegram-role-management-guide',
    path: '/blog/telegram-role-management-guide',
    getParentRoute: () => rootRouteImport,
  } as any)
const BrandAssetSplatRoute = BrandAssetSplatRouteImport.update({
  id: '/brand-asset/$',
  path: '/brand-asset/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscordInteractionsRoute = DiscordInteractionsRouteImport.update({
  id: '/discord/interactions',
  path: '/discord/interactions',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscordLinkedRoleRoute = DiscordLinkedRoleRouteImport.update({
  id: '/discord/linked-role',
  path: '/discord/linked-role',
  getParentRoute: () => rootRouteImport,
} as any)
const GSlugRoute = GSlugRouteImport.update({
  id: '/g/$slug',
  path: '/g/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GateMediaSplatRoute = GateMediaSplatRouteImport.update({
  id: '/gate-media/$',
  path: '/gate-media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const GatesIndexRoute = GatesIndexRouteImport.update({
  id: '/gates/',
  path: '/gates/',
  getParentRoute: () => rootRouteImport,
} as any)
const GatesIdRoute = GatesIdRouteImport.update({
  id: '/gates/$id',
  path: '/gates/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRotatingCtaRoute = PreviewRotatingCtaRouteImport.update({
  id: '/preview/rotating-cta',
  path: '/preview/rotating-cta',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalTelegramDestinationRoute =
  ApiInternalTelegramDestinationRouteImport.update({
    id: '/api/internal/telegram-destination',
    path: '/api/internal/telegram-destination',
    getParentRoute: () => rootRouteImport,
  } as any)
const DiscordLinkedRoleCallbackRoute =
  DiscordLinkedRoleCallbackRouteImport.update({
    id: '/callback',
    path: '/callback',
    getParentRoute: () => DiscordLinkedRoleRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/activate': typeof ActivateRoute
  '/admin': typeof AdminRoute
  '/brands': typeof BrandsRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/gate': typeof GateRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/moderation': typeof ModerationRoute
  '/not-eligible': typeof NotEligibleRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/standards': typeof StandardsRoute
  '/terms': typeof TermsRoute
  '/upgrade': typeof UpgradeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/blog/telegram-role-management-guide': typeof BlogTelegramRoleManagementGuideRoute
  '/brand-asset/$': typeof BrandAssetSplatRoute
  '/discord/interactions': typeof DiscordInteractionsRoute
  '/discord/linked-role': typeof DiscordLinkedRoleRouteWithChildren
  '/g/$slug': typeof GSlugRoute
  '/gate-media/$': typeof GateMediaSplatRoute
  '/gates/$id': typeof GatesIdRoute
  '/preview/rotating-cta': typeof PreviewRotatingCtaRoute
  '/gates/': typeof GatesIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/internal/telegram-destination': typeof ApiInternalTelegramDestinationRoute
  '/discord/linked-role/callback': typeof DiscordLinkedRoleCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/activate': typeof ActivateRoute
  '/admin': typeof AdminRoute
  '/brands': typeof BrandsRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/gate': typeof GateRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/moderation': typeof ModerationRoute
  '/not-eligible': typeof NotEligibleRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/standards': typeof StandardsRoute
  '/terms': typeof TermsRoute
  '/upgrade': typeof UpgradeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/blog/telegram-role-management-guide': typeof BlogTelegramRoleManagementGuideRoute
  '/brand-asset/$': typeof BrandAssetSplatRoute
  '/discord/interactions': typeof DiscordInteractionsRoute
  '/discord/linked-role': typeof DiscordLinkedRoleRouteWithChildren
  '/g/$slug': typeof GSlugRoute
  '/gate-media/$': typeof GateMediaSplatRoute
  '/gates/$id': typeof GatesIdRoute
  '/preview/rotating-cta': typeof PreviewRotatingCtaRoute
  '/gates': typeof GatesIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/internal/telegram-destination': typeof ApiInternalTelegramDestinationRoute
  '/discord/linked-role/callback': typeof DiscordLinkedRoleCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/activate': typeof ActivateRoute
  '/admin': typeof AdminRoute
  '/brands': typeof BrandsRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/gate': typeof GateRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/moderation': typeof ModerationRoute
  '/not-eligible': typeof NotEligibleRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/standards': typeof StandardsRoute
  '/terms': typeof TermsRoute
  '/upgrade': typeof UpgradeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/blog/telegram-role-management-guide': typeof BlogTelegramRoleManagementGuideRoute
  '/brand-asset/$': typeof BrandAssetSplatRoute
  '/discord/interactions': typeof DiscordInteractionsRoute
  '/discord/linked-role': typeof DiscordLinkedRoleRouteWithChildren
  '/g/$slug': typeof GSlugRoute
  '/gate-media/$': typeof GateMediaSplatRoute
  '/gates/$id': typeof GatesIdRoute
  '/preview/rotating-cta': typeof PreviewRotatingCtaRoute
  '/gates/': typeof GatesIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/internal/telegram-destination': typeof ApiInternalTelegramDestinationRoute
  '/discord/linked-role/callback': typeof DiscordLinkedRoleCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access'
    | '/activate'
    | '/admin'
    | '/brands'
    | '/dashboard'
    | '/demo'
    | '/gate'
    | '/login'
    | '/mcp'
    | '/moderation'
    | '/not-eligible'
    | '/privacy'
    | '/sitemap.xml'
    | '/standards'
    | '/terms'
    | '/upgrade'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/blog/telegram-role-management-guide'
    | '/brand-asset/$'
    | '/discord/interactions'
    | '/discord/linked-role'
    | '/g/$slug'
    | '/gate-media/$'
    | '/gates/$id'
    | '/preview/rotating-cta'
    | '/gates/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/internal/telegram-destination'
    | '/discord/linked-role/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access'
    | '/activate'
    | '/admin'
    | '/brands'
    | '/dashboard'
    | '/demo'
    | '/gate'
    | '/login'
    | '/mcp'
    | '/moderation'
    | '/not-eligible'
    | '/privacy'
    | '/sitemap.xml'
    | '/standards'
    | '/terms'
    | '/upgrade'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/blog/telegram-role-management-guide'
    | '/brand-asset/$'
    | '/discord/interactions'
    | '/discord/linked-role'
    | '/g/$slug'
    | '/gate-media/$'
    | '/gates/$id'
    | '/preview/rotating-cta'
    | '/gates'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/internal/telegram-destination'
    | '/discord/linked-role/callback'
  id:
    | '__root__'
    | '/'
    | '/access'
    | '/activate'
    | '/admin'
    | '/brands'
    | '/dashboard'
    | '/demo'
    | '/gate'
    | '/login'
    | '/mcp'
    | '/moderation'
    | '/not-eligible'
    | '/privacy'
    | '/sitemap.xml'
    | '/standards'
    | '/terms'
    | '/upgrade'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/blog/telegram-role-management-guide'
    | '/brand-asset/$'
    | '/discord/interactions'
    | '/discord/linked-role'
    | '/g/$slug'
    | '/gate-media/$'
    | '/gates/$id'
    | '/preview/rotating-cta'
    | '/gates/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/internal/telegram-destination'
    | '/discord/linked-role/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessRoute: typeof AccessRoute
  ActivateRoute: typeof ActivateRoute
  AdminRoute: typeof AdminRoute
  BrandsRoute: typeof BrandsRoute
  DashboardRoute: typeof DashboardRoute
  DemoRoute: typeof DemoRoute
  GateRoute: typeof GateRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  ModerationRoute: typeof ModerationRoute
  NotEligibleRoute: typeof NotEligibleRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StandardsRoute: typeof StandardsRoute
  TermsRoute: typeof TermsRoute
  UpgradeRoute: typeof UpgradeRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  BlogTelegramRoleManagementGuideRoute: typeof BlogTelegramRoleManagementGuideRoute
  BrandAssetSplatRoute: typeof BrandAssetSplatRoute
  DiscordInteractionsRoute: typeof DiscordInteractionsRoute
  DiscordLinkedRoleRoute: typeof DiscordLinkedRoleRouteWithChildren
  GSlugRoute: typeof GSlugRoute
  GateMediaSplatRoute: typeof GateMediaSplatRoute
  GatesIdRoute: typeof GatesIdRoute
  PreviewRotatingCtaRoute: typeof PreviewRotatingCtaRoute
  GatesIndexRoute: typeof GatesIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiInternalTelegramDestinationRoute: typeof ApiInternalTelegramDestinationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate': {
      id: '/activate'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof ActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gate': {
      id: '/gate'
      path: '/gate'
      fullPath: '/gate'
      preLoaderRoute: typeof GateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderation': {
      id: '/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof ModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-eligible': {
      id: '/not-eligible'
      path: '/not-eligible'
      fullPath: '/not-eligible'
      preLoaderRoute: typeof NotEligibleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standards': {
      id: '/standards'
      path: '/standards'
      fullPath: '/standards'
      preLoaderRoute: typeof StandardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/telegram-role-management-guide': {
      id: '/blog/telegram-role-management-guide'
      path: '/blog/telegram-role-management-guide'
      fullPath: '/blog/telegram-role-management-guide'
      preLoaderRoute: typeof BlogTelegramRoleManagementGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-asset/$': {
      id: '/brand-asset/$'
      path: '/brand-asset/$'
      fullPath: '/brand-asset/$'
      preLoaderRoute: typeof BrandAssetSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discord/interactions': {
      id: '/discord/interactions'
      path: '/discord/interactions'
      fullPath: '/discord/interactions'
      preLoaderRoute: typeof DiscordInteractionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discord/linked-role': {
      id: '/discord/linked-role'
      path: '/discord/linked-role'
      fullPath: '/discord/linked-role'
      preLoaderRoute: typeof DiscordLinkedRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$slug': {
      id: '/g/$slug'
      path: '/g/$slug'
      fullPath: '/g/$slug'
      preLoaderRoute: typeof GSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gate-media/$': {
      id: '/gate-media/$'
      path: '/gate-media/$'
      fullPath: '/gate-media/$'
      preLoaderRoute: typeof GateMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gates/': {
      id: '/gates/'
      path: '/gates'
      fullPath: '/gates/'
      preLoaderRoute: typeof GatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gates/$id': {
      id: '/gates/$id'
      path: '/gates/$id'
      fullPath: '/gates/$id'
      preLoaderRoute: typeof GatesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/rotating-cta': {
      id: '/preview/rotating-cta'
      path: '/preview/rotating-cta'
      fullPath: '/preview/rotating-cta'
      preLoaderRoute: typeof PreviewRotatingCtaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/telegram-destination': {
      id: '/api/internal/telegram-destination'
      path: '/api/internal/telegram-destination'
      fullPath: '/api/internal/telegram-destination'
      preLoaderRoute: typeof ApiInternalTelegramDestinationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discord/linked-role/callback': {
      id: '/discord/linked-role/callback'
      path: '/callback'
      fullPath: '/discord/linked-role/callback'
      preLoaderRoute: typeof DiscordLinkedRoleCallbackRouteImport
      parentRoute: typeof DiscordLinkedRoleRoute
    }
  }
}

interface DiscordLinkedRoleRouteChildren {
  DiscordLinkedRoleCallbackRoute: typeof DiscordLinkedRoleCallbackRoute
}

const DiscordLinkedRoleRouteChildren: DiscordLinkedRoleRouteChildren = {
  DiscordLinkedRoleCallbackRoute: DiscordLinkedRoleCallbackRoute,
}

const DiscordLinkedRoleRouteWithChildren =
  DiscordLinkedRoleRoute._addFileChildren(DiscordLinkedRoleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessRoute: AccessRoute,
  ActivateRoute: ActivateRoute,
  AdminRoute: AdminRoute,
  BrandsRoute: BrandsRoute,
  DashboardRoute: DashboardRoute,
  DemoRoute: DemoRoute,
  GateRoute: GateRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  ModerationRoute: ModerationRoute,
  NotEligibleRoute: NotEligibleRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StandardsRoute: StandardsRoute,
  TermsRoute: TermsRoute,
  UpgradeRoute: UpgradeRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  BlogTelegramRoleManagementGuideRoute: BlogTelegramRoleManagementGuideRoute,
  BrandAssetSplatRoute: BrandAssetSplatRoute,
  DiscordInteractionsRoute: DiscordInteractionsRoute,
  DiscordLinkedRoleRoute: DiscordLinkedRoleRouteWithChildren,
  GSlugRoute: GSlugRoute,
  GateMediaSplatRoute: GateMediaSplatRoute,
  GatesIdRoute: GatesIdRoute,
  PreviewRotatingCtaRoute: PreviewRotatingCtaRoute,
  GatesIndexRoute: GatesIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiInternalTelegramDestinationRoute: ApiInternalTelegramDestinationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
