/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivateRouteImport } from './routes/activate'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as GateRouteImport } from './routes/gate'
import { Route as LoginRouteImport } from './routes/login'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ModerationRouteImport } from './routes/moderation'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as ZzGateHarnessRouteImport } from './routes/zz-gate-harness'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthNeonCallbackRouteImport } from './routes/auth.neon-callback'
import { Route as AuthNeonStartRouteImport } from './routes/auth.neon-start'
import { Route as AuthSocialRouteImport } from './routes/auth.social'
import { Route as AuthStartRouteImport } from './routes/auth.start'
import { Route as BlogTelegramRoleManagementGuideRouteImport } from './routes/blog.telegram-role-management-guide'
import { Route as BrandAssetSplatRouteImport } from './routes/brand-asset.$'
import { Route as GSlugRouteImport } from './routes/g.$slug'
import { Route as GateMediaSplatRouteImport } from './routes/gate-media.$'
import { Route as GatesIndexRouteImport } from './routes/gates.index'
import { Route as GatesIdRouteImport } from './routes/gates.$id'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiStripeWebhookRouteImport } from './routes/api.stripe.webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateRoute = ActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const GateRoute = GateRouteImport.update({
  id: '/gate',
  path: '/gate',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ModerationRoute = ModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ZzGateHarnessRoute = ZzGateHarnessRouteImport.update({
  id: '/zz-gate-harness',
  path: '/zz-gate-harness',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthNeonCallbackRoute = AuthNeonCallbackRouteImport.update({
  id: '/auth/neon-callback',
  path: '/auth/neon-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthNeonStartRoute = AuthNeonStartRouteImport.update({
  id: '/auth/neon-start',
  path: '/auth/neon-start',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSocialRoute = AuthSocialRouteImport.update({
  id: '/auth/social',
  path: '/auth/social',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthStartRoute = AuthStartRouteImport.update({
  id: '/auth/start',
  path: '/auth/start',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogTelegramRoleManagementGuideRoute =
  BlogTelegramRoleManagementGuideRouteImport.update({
    id: '/blog/telegram-role-management-guide',
    path: '/blog/telegram-role-management-guide',
    getParentRoute: () => rootRouteImport,
  } as any)
const BrandAssetSplatRoute = BrandAssetSplatRouteImport.update({
  id: '/brand-asset/$',
  path: '/brand-asset/$',
  getParentRoute: () => rootRouteImport,
} as any)
const GSlugRoute = GSlugRouteImport.update({
  id: '/g/$slug',
  path: '/g/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GateMediaSplatRoute = GateMediaSplatRouteImport.update({
  id: '/gate-media/$',
  path: '/gate-media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const GatesIndexRoute = GatesIndexRouteImport.update({
  id: '/gates/',
  path: '/gates/',
  getParentRoute: () => rootRouteImport,
} as any)
const GatesIdRoute = GatesIdRouteImport.update({
  id: '/gates/$id',
  path: '/gates/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/admin': typeof AdminRoute
  '/brands': typeof BrandsRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/gate': typeof GateRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/moderation': typeof ModerationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/upgrade': typeof UpgradeRoute
  '/verify': typeof VerifyRoute
  '/zz-gate-harness': typeof ZzGateHarnessRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/neon-callback': typeof AuthNeonCallbackRoute
  '/auth/neon-start': typeof AuthNeonStartRoute
  '/auth/social': typeof AuthSocialRoute
  '/auth/start': typeof AuthStartRoute
  '/blog/telegram-role-management-guide': typeof BlogTelegramRoleManagementGuideRoute
  '/brand-asset/$': typeof BrandAssetSplatRoute
  '/g/$slug': typeof GSlugRoute
  '/gate-media/$': typeof GateMediaSplatRoute
  '/gates/$id': typeof GatesIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/gates/': typeof GatesIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/admin': typeof AdminRoute
  '/brands': typeof BrandsRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/gate': typeof GateRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/moderation': typeof ModerationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/upgrade': typeof UpgradeRoute
  '/verify': typeof VerifyRoute
  '/zz-gate-harness': typeof ZzGateHarnessRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/neon-callback': typeof AuthNeonCallbackRoute
  '/auth/neon-start': typeof AuthNeonStartRoute
  '/auth/social': typeof AuthSocialRoute
  '/auth/start': typeof AuthStartRoute
  '/blog/telegram-role-management-guide': typeof BlogTelegramRoleManagementGuideRoute
  '/brand-asset/$': typeof BrandAssetSplatRoute
  '/g/$slug': typeof GSlugRoute
  '/gate-media/$': typeof GateMediaSplatRoute
  '/gates/$id': typeof GatesIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/gates': typeof GatesIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activate': typeof ActivateRoute
  '/admin': typeof AdminRoute
  '/brands': typeof BrandsRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/gate': typeof GateRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/moderation': typeof ModerationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/upgrade': typeof UpgradeRoute
  '/verify': typeof VerifyRoute
  '/zz-gate-harness': typeof ZzGateHarnessRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/neon-callback': typeof AuthNeonCallbackRoute
  '/auth/neon-start': typeof AuthNeonStartRoute
  '/auth/social': typeof AuthSocialRoute
  '/auth/start': typeof AuthStartRoute
  '/blog/telegram-role-management-guide': typeof BlogTelegramRoleManagementGuideRoute
  '/brand-asset/$': typeof BrandAssetSplatRoute
  '/g/$slug': typeof GSlugRoute
  '/gate-media/$': typeof GateMediaSplatRoute
  '/gates/$id': typeof GatesIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/gates/': typeof GatesIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activate'
    | '/admin'
    | '/brands'
    | '/dashboard'
    | '/demo'
    | '/gate'
    | '/login'
    | '/mcp'
    | '/moderation'
    | '/sitemap.xml'
    | '/upgrade'
    | '/verify'
    | '/zz-gate-harness'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/auth/callback'
    | '/auth/neon-callback'
    | '/auth/neon-start'
    | '/auth/social'
    | '/auth/start'
    | '/blog/telegram-role-management-guide'
    | '/brand-asset/$'
    | '/g/$slug'
    | '/gate-media/$'
    | '/gates/$id'
    | '/invite/$token'
    | '/gates/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/stripe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activate'
    | '/admin'
    | '/brands'
    | '/dashboard'
    | '/demo'
    | '/gate'
    | '/login'
    | '/mcp'
    | '/moderation'
    | '/sitemap.xml'
    | '/upgrade'
    | '/verify'
    | '/zz-gate-harness'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/auth/callback'
    | '/auth/neon-callback'
    | '/auth/neon-start'
    | '/auth/social'
    | '/auth/start'
    | '/blog/telegram-role-management-guide'
    | '/brand-asset/$'
    | '/g/$slug'
    | '/gate-media/$'
    | '/gates/$id'
    | '/invite/$token'
    | '/gates'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/stripe/webhook'
  id:
    | '__root__'
    | '/'
    | '/activate'
    | '/admin'
    | '/brands'
    | '/dashboard'
    | '/demo'
    | '/gate'
    | '/login'
    | '/mcp'
    | '/moderation'
    | '/sitemap.xml'
    | '/upgrade'
    | '/verify'
    | '/zz-gate-harness'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/auth/callback'
    | '/auth/neon-callback'
    | '/auth/neon-start'
    | '/auth/social'
    | '/auth/start'
    | '/blog/telegram-role-management-guide'
    | '/brand-asset/$'
    | '/g/$slug'
    | '/gate-media/$'
    | '/gates/$id'
    | '/invite/$token'
    | '/gates/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/stripe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivateRoute: typeof ActivateRoute
  AdminRoute: typeof AdminRoute
  BrandsRoute: typeof BrandsRoute
  DashboardRoute: typeof DashboardRoute
  DemoRoute: typeof DemoRoute
  GateRoute: typeof GateRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  ModerationRoute: typeof ModerationRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UpgradeRoute: typeof UpgradeRoute
  VerifyRoute: typeof VerifyRoute
  ZzGateHarnessRoute: typeof ZzGateHarnessRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthNeonCallbackRoute: typeof AuthNeonCallbackRoute
  AuthNeonStartRoute: typeof AuthNeonStartRoute
  AuthSocialRoute: typeof AuthSocialRoute
  AuthStartRoute: typeof AuthStartRoute
  BlogTelegramRoleManagementGuideRoute: typeof BlogTelegramRoleManagementGuideRoute
  BrandAssetSplatRoute: typeof BrandAssetSplatRoute
  GSlugRoute: typeof GSlugRoute
  GateMediaSplatRoute: typeof GateMediaSplatRoute
  GatesIdRoute: typeof GatesIdRoute
  InviteTokenRoute: typeof InviteTokenRoute
  GatesIndexRoute: typeof GatesIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate': {
      id: '/activate'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof ActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gate': {
      id: '/gate'
      path: '/gate'
      fullPath: '/gate'
      preLoaderRoute: typeof GateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderation': {
      id: '/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof ModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zz-gate-harness': {
      id: '/zz-gate-harness'
      path: '/zz-gate-harness'
      fullPath: '/zz-gate-harness'
      preLoaderRoute: typeof ZzGateHarnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/neon-callback': {
      id: '/auth/neon-callback'
      path: '/auth/neon-callback'
      fullPath: '/auth/neon-callback'
      preLoaderRoute: typeof AuthNeonCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/neon-start': {
      id: '/auth/neon-start'
      path: '/auth/neon-start'
      fullPath: '/auth/neon-start'
      preLoaderRoute: typeof AuthNeonStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/social': {
      id: '/auth/social'
      path: '/auth/social'
      fullPath: '/auth/social'
      preLoaderRoute: typeof AuthSocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/start': {
      id: '/auth/start'
      path: '/auth/start'
      fullPath: '/auth/start'
      preLoaderRoute: typeof AuthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/telegram-role-management-guide': {
      id: '/blog/telegram-role-management-guide'
      path: '/blog/telegram-role-management-guide'
      fullPath: '/blog/telegram-role-management-guide'
      preLoaderRoute: typeof BlogTelegramRoleManagementGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-asset/$': {
      id: '/brand-asset/$'
      path: '/brand-asset/$'
      fullPath: '/brand-asset/$'
      preLoaderRoute: typeof BrandAssetSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$slug': {
      id: '/g/$slug'
      path: '/g/$slug'
      fullPath: '/g/$slug'
      preLoaderRoute: typeof GSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gate-media/$': {
      id: '/gate-media/$'
      path: '/gate-media/$'
      fullPath: '/gate-media/$'
      preLoaderRoute: typeof GateMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gates/': {
      id: '/gates/'
      path: '/gates'
      fullPath: '/gates/'
      preLoaderRoute: typeof GatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gates/$id': {
      id: '/gates/$id'
      path: '/gates/$id'
      fullPath: '/gates/$id'
      preLoaderRoute: typeof GatesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivateRoute: ActivateRoute,
  AdminRoute: AdminRoute,
  BrandsRoute: BrandsRoute,
  DashboardRoute: DashboardRoute,
  DemoRoute: DemoRoute,
  GateRoute: GateRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  ModerationRoute: ModerationRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UpgradeRoute: UpgradeRoute,
  VerifyRoute: VerifyRoute,
  ZzGateHarnessRoute: ZzGateHarnessRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthNeonCallbackRoute: AuthNeonCallbackRoute,
  AuthNeonStartRoute: AuthNeonStartRoute,
  AuthSocialRoute: AuthSocialRoute,
  AuthStartRoute: AuthStartRoute,
  BlogTelegramRoleManagementGuideRoute: BlogTelegramRoleManagementGuideRoute,
  BrandAssetSplatRoute: BrandAssetSplatRoute,
  GSlugRoute: GSlugRoute,
  GateMediaSplatRoute: GateMediaSplatRoute,
  GatesIdRoute: GatesIdRoute,
  InviteTokenRoute: InviteTokenRoute,
  GatesIndexRoute: GatesIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
