name = "fenrir-redirects"
main = "worker.js"
compatibility_date = "2026-08-01"
routes = [
  { pattern = "myfenrir.com/*", zone_name = "myfenrir.com" },
  { pattern = "www.myfenrir.com/*", zone_name = "myfenrir.com" }
]
